// DSS/DSS/components/base/DssButton/1-structure/DssButton.vue
<template>
  <component
    :is="componentType"
    :type="nativeType"
    :to="to"
    :replace="replace"
    :disabled="disabled || loading"
    :class="buttonClasses"
    :style="buttonStyle"
    :tabindex="computedTabindex"
    v-bind="$attrs"
    @click="handleClick"
  >
    <!-- Loading spinner -->
    <span v-if="loading && percentage === null" class="dss-button__loading">
      <span class="dss-button__spinner"></span>
    </span>

    <!-- Progress bar (percentage mode) -->
    <span
      v-if="loading && percentage !== null"
      class="dss-button__progress"
      :class="{ 'dss-button__progress--dark': darkPercentage }"
    >
      <span
        class="dss-button__progress-indicator"
        :style="percentageStyle"
      ></span>
    </span>

    <!-- Icon Left (before label) -->
    <span v-if="computedIconLeft && !loading" class="dss-button__icon dss-button__icon--left">
      {{ computedIconLeft }}
    </span>

    <!-- Label/Content -->
    <span v-if="label || $slots.default" class="dss-button__label">
      <slot>{{ label }}</slot>
    </span>

    <!-- Icon Right (after label) -->
    <span v-if="computedIconRight && !loading" class="dss-button__icon dss-button__icon--right">
      {{ computedIconRight }}
    </span>

    <!-- Ripple effect container (opcional) -->
    <span v-if="ripple" class="dss-button__ripple"></span>
  </component>
</template>

<script>
export default {
  name: 'DssButton',

  inheritAttrs: false,

  props: {
    // Content
    label: {
      type: String,
      default: ''
    },
    // Ícone à esquerda (compatível com Quasar)
    icon: {
      type: String,
      default: ''
    },
    // Ícone à direita (compatível com Quasar)
    iconRight: {
      type: String,
      default: ''
    },

    // Visual Variant
    variant: {
      type: String,
      default: 'elevated',
      validator: (value) => ['elevated', 'flat', 'outline', 'unelevated', 'push', 'glossy'].includes(value)
    },

    // Color
    color: {
      type: String,
      default: 'primary',
      validator: (value) => ['primary', 'secondary', 'tertiary', 'accent', 'positive', 'negative', 'warning', 'info'].includes(value)
    },

    // Size
    size: {
      type: String,
      default: 'md',
      validator: (value) => ['xs', 'sm', 'md', 'lg', 'xl'].includes(value)
    },

    // Shape
    round: {
      type: Boolean,
      default: false
    },
    square: {
      type: Boolean,
      default: false
    },

    // States
    loading: {
      type: Boolean,
      default: false
    },
    disabled: {
      type: Boolean,
      default: false
    },

    // Loading Progress (compatível com Quasar)
    percentage: {
      type: Number,
      default: null,
      validator: (value) => value === null || (value >= 0 && value <= 100)
    },
    darkPercentage: {
      type: Boolean,
      default: false
    },

    // Behavior
    type: {
      type: String,
      default: 'button',
      validator: (value) => ['button', 'submit', 'reset'].includes(value)
    },

    // Router (if using Vue Router)
    to: {
      type: [String, Object],
      default: null
    },
    replace: {
      type: Boolean,
      default: false
    },

    // Brand
    brand: {
      type: String,
      default: null,
      validator: (value) => !value || ['hub', 'water', 'waste'].includes(value)
    },

    // Dense
    dense: {
      type: Boolean,
      default: false
    },

    // No caps (disable uppercase transform)
    noCaps: {
      type: Boolean,
      default: false
    },

    // Interaction (compatível com Quasar)
    ripple: {
      type: Boolean,
      default: false
    },
    tabindex: {
      type: [Number, String],
      default: null
    },

    // Layout (compatível com Quasar)
    align: {
      type: String,
      default: 'center',
      validator: (value) => ['left', 'center', 'right', 'between', 'around', 'evenly'].includes(value)
    },
    stack: {
      type: Boolean,
      default: false
    },
    stretch: {
      type: Boolean,
      default: false
    },
    noWrap: {
      type: Boolean,
      default: false
    },
    padding: {
      type: String,
      default: null // null = usa padding padrão do DSS
    }
  },

  computed: {
    componentType() {
      if (this.to) {
        return 'router-link';
      }
      return 'button';
    },

    nativeType() {
      return this.to ? null : this.type;
    },

    // Ícone à esquerda (compatível com Quasar)
    computedIconLeft() {
      return this.icon || '';
    },

    // Ícone à direita (compatível com Quasar)
    computedIconRight() {
      return this.iconRight || '';
    },

    buttonClasses() {
      // Determina classes de cor seguindo padrão Quasar
      // flat/outline: usa text-{color}
      // outros: usa bg-{color} + text-white
      // ⚠️ EXCETO se tiver brand (brand tem prioridade)
      let colorClasses = '';

      // Se tem brand, NÃO aplicar classes utilitárias de cor
      // (brand usa CSS próprio sem !important)
      if (!this.brand) {
        if (this.variant === 'flat' || this.variant === 'outline') {
          colorClasses = `text-${this.color}`;
        } else {
          colorClasses = `bg-${this.color} text-white`;
        }
      }

      return [
        'dss-button',
        `dss-button--${this.variant}`,
        colorClasses, // Classes utilitárias (.bg-primary, .text-primary) - vazio se brand
        `dss-button--${this.size}`,
        {
          'dss-button--round': this.round,
          'dss-button--square': this.square,
          'dss-button--loading': this.loading,
          'dss-button--disabled': this.disabled,
          'dss-button--dense': this.dense,
          'dss-button--no-caps': this.noCaps,
          'dss-button--icon-only': (this.computedIconLeft || this.computedIconRight) && !this.label && !this.$slots.default,
          [`dss-button--brand-${this.brand}`]: this.brand,
          // Layout classes (compatível com Quasar)
          [`dss-button--align-${this.align}`]: this.align !== 'center',
          'dss-button--stack': this.stack,
          'dss-button--stretch': this.stretch,
          'dss-button--no-wrap': this.noWrap
        }
      ];
    },

    // Estilo inline para padding customizável (compatível com Quasar)
    buttonStyle() {
      const style = {};

      if (this.padding) {
        style.padding = this.padding;
      }

      return style;
    },

    // Barra de progresso (compatível com Quasar)
    percentageStyle() {
      if (this.percentage === null) return null;

      return {
        transform: `translateX(${this.percentage - 100}%)`
      };
    },

    // Tabindex computado (compatível com Quasar)
    computedTabindex() {
      if (this.disabled || this.loading) return -1;
      return this.tabindex !== null ? this.tabindex : 0;
    }
  },

  methods: {
    handleClick(event) {
      if (!this.disabled && !this.loading) {
        this.$emit('click', event);
      }
    }
  }
}
</script>

<!-- Estilos carregados globalmente via dss-full.css -->

// Grid Inspector/src/app/components/dss/DssButton/DssButton.tsx
import React, { ButtonHTMLAttributes } from 'react';
import './dss-button.css';

/**
 * DssButton - Componente de botão do Design System Sansys
 * 
 * Wrapper DSS compatível com a API do Quasar QBtn, com extensões de brandabilidade e acessibilidade.
 * 
 * FUNCIONALIDADES:
 * - 6 variantes (elevated, flat, outline, unelevated, push, glossy)
 * - 5 tamanhos (xs, sm, md, lg, xl)
 * - 8 cores semânticas + brandabilidade (hub, water, waste)
 * - Loading com progresso determinístico (percentage)
 * - Ripple effect Material Design
 * - Layout avançado (align, stack, stretch, padding)
 * - Router integration (to, replace)
 * - WCAG 2.1 AA compliant
 * 
 * @version 2.1 (React adaptation)
 * @see https://github.com/hebertchaves/design-system-sansys/tree/main/components/base/DssButton
 */

export interface DssButtonProps extends ButtonHTMLAttributes<HTMLButtonElement> {
  /** Texto do botão */
  label?: string;
  /** Ícone à esquerda (Material Icons) */
  icon?: string;
  /** Ícone à direita (Material Icons) */
  iconRight?: string;
  /** Variante visual do botão */
  variant?: 'elevated' | 'flat' | 'outline' | 'unelevated' | 'push' | 'glossy' | 'text';
  /** Cor semântica */
  color?: 'primary' | 'secondary' | 'tertiary' | 'accent' | 'positive' | 'negative' | 'warning' | 'info' | 'dark';
  /** Tamanho do botão */
  size?: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
  /** Brandabilidade Sansys */
  brand?: 'hub' | 'water' | 'waste';
  /** Bordas completamente arredondadas */
  round?: boolean;
  /** Bordas quadradas (sem border-radius) */
  square?: boolean;
  /** Loading state */
  loading?: boolean;
  /** Progresso determinístico (0-100) */
  percentage?: number;
  /** Estilo escuro da barra de progresso */
  darkPercentage?: boolean;
  /** Efeito ripple Material Design */
  ripple?: boolean;
  /** Alinhamento horizontal do conteúdo */
  align?: 'left' | 'center' | 'right' | 'between' | 'around' | 'evenly';
  /** Layout vertical (ícone acima do label) */
  stack?: boolean;
  /** Expande para preencher largura disponível */
  stretch?: boolean;
  /** Previne quebra de texto */
  noWrap?: boolean;
  /** Versão compacta do botão */
  dense?: boolean;
  /** Desabilita transformação uppercase */
  noCaps?: boolean;
  /** Tipo nativo do button HTML */
  type?: 'button' | 'submit' | 'reset';
  /** Rota de navegação (React Router) */
  to?: string;
  /** Usa replace ao invés de push */
  replace?: boolean;
  /** Children */
  children?: React.ReactNode;
  /** Classes CSS adicionais */
  className?: string;
}

export function DssButton({
  label,
  icon,
  iconRight,
  variant = 'elevated',
  color = 'primary',
  size = 'md',
  brand,
  round = false,
  square = false,
  loading = false,
  percentage,
  darkPercentage = false,
  ripple = false,
  align = 'center',
  stack = false,
  stretch = false,
  noWrap = false,
  dense = false,
  noCaps = false,
  type = 'button',
  to,
  replace = false,
  disabled,
  className = '',
  children,
  style,
  ...props
}: DssButtonProps) {
  // Detecta se é icon-only (só ícone, sem label/children)
  const isIconOnly = !label && !children && (icon || iconRight);
  
  const classes = [
    'dss-button',
    `dss-button--${variant}`,
    `dss-button--${color}`,
    `dss-button--${size}`,
    brand && `dss-button--brand-${brand}`,
    round && 'dss-button--round',
    square && 'dss-button--square',
    loading && 'dss-button--loading',
    disabled && 'dss-button--disabled',
    ripple && 'dss-button--ripple',
    `dss-button--align-${align}`,
    stack && 'dss-button--stack',
    stretch && 'dss-button--stretch',
    noWrap && 'dss-button--no-wrap',
    dense && 'dss-button--dense',
    noCaps && 'dss-button--no-caps',
    isIconOnly && 'dss-button--icon-only',
    className
  ].filter(Boolean).join(' ');

  // Router integration (React Router would be handled differently, simplified here)
  const handleClick = (e: React.MouseEvent<HTMLButtonElement>) => {
    if (to && !disabled && !loading) {
      // In a real app, you'd use useNavigate from react-router
      console.warn('Router integration: navigate to', to);
    }
    if (props.onClick && !disabled && !loading) {
      props.onClick(e);
    }
  };

  const showPercentage = loading && percentage !== undefined && percentage !== null;

  return (
    <button
      type={type}
      className={classes}
      disabled={disabled || loading}
      aria-disabled={disabled || loading}
      style={style}
      {...props}
      onClick={handleClick}
    >
      {/* Barra de progresso determinística */}
      {showPercentage && (
        <span 
          className={`dss-button__progress ${darkPercentage ? 'dss-button__progress--dark' : ''}`}
          style={{ width: `${percentage}%` }}
          role="progressbar"
          aria-valuenow={percentage}
          aria-valuemin={0}
          aria-valuemax={100}
        />
      )}

      {/* Spinner de loading */}
      {loading && !showPercentage && (
        <span className="dss-button__spinner" aria-hidden="true">
          <svg className="dss-button__spinner-icon" viewBox="0 0 24 24">
            <circle 
              className="dss-button__spinner-circle" 
              cx="12" 
              cy="12" 
              r="10" 
              fill="none" 
              strokeWidth="3"
            />
          </svg>
        </span>
      )}
      
      {/* Ícone esquerdo */}
      {!loading && icon && (
        <span className="dss-button__icon dss-button__icon--left material-icons" aria-hidden="true">
          {icon}
        </span>
      )}
      
      {/* Conteúdo */}
      {!isIconOnly && (
        <span className="dss-button__content">
          {children || label}
        </span>
      )}
      
      {/* Ícone direito */}
      {!loading && iconRight && (
        <span className="dss-button__icon dss-button__icon--right material-icons" aria-hidden="true">
          {iconRight}
        </span>
      )}
    </button>
  );
}
