// Grid Inspector/src/app/components/dss/DssBadge/DssBadge.tsx
import React from 'react';
import './dss-badge.css';

/**
 * DssBadge - Badge component DSS
 * 
 * Wrapper DSS baseado no QBadge, com API pública governada pelo Design System Sansys.
 * 
 * FUNCIONALIDADES:
 * - Cores semânticas completas + brandabilidade
 * - Variantes: default, transparent, outline, rounded
 * - Floating badge (notificações)
 * - Dot indicator (vazio)
 * - Multi-line support
 * - Alinhamento vertical
 * 
 * @version 2.3 (React adaptation)
 * @see https://github.com/hebertchaves/design-system-sansys/tree/main/components/base/DssBadge
 */

export interface DssBadgeProps extends React.HTMLAttributes<HTMLSpanElement> {
  /** Conteúdo do badge */
  label?: string | number;
  /** Cor semântica */
  color?: 'primary' | 'secondary' | 'tertiary' | 'accent' | 'positive' | 'negative' | 'warning' | 'info';
  /** Cor do texto (sobrescreve cor padrão) */
  textColor?: 'primary' | 'secondary' | 'tertiary' | 'accent' | 'positive' | 'negative' | 'warning' | 'info' | 'white' | 'dark';
  /** Brand (hub, water, waste) */
  brand?: 'hub' | 'water' | 'waste';
  /** Badge posicionado de forma absoluta (top-right) */
  floating?: boolean;
  /** Alinhamento vertical */
  align?: 'top' | 'middle' | 'bottom';
  /** Badge com fundo transparente */
  transparent?: boolean;
  /** Badge com borda colorida (sem preenchimento) */
  outline?: boolean;
  /** Badge com bordas mais arredondadas */
  rounded?: boolean;
  /** Permite texto em múltiplas linhas */
  multiLine?: boolean;
  /** ARIA label para screen readers */
  ariaLabel?: string;
  /** Children (substitui label) */
  children?: React.ReactNode;
  /** Classes CSS adicionais */
  className?: string;
}

export function DssBadge({
  label,
  color = 'primary',
  textColor,
  brand,
  floating = false,
  align,
  transparent = false,
  outline = false,
  rounded = false,
  multiLine = false,
  ariaLabel,
  children,
  className = '',
  ...props
}: DssBadgeProps) {
  // Badge vazio = dot indicator
  const isEmpty = !label && !children;

  const classes = [
    'dss-badge',
    `dss-badge--${color}`,
    textColor && `dss-badge--text-${textColor}`,
    brand && `dss-badge--brand-${brand}`,
    floating && 'dss-badge--floating',
    align && `dss-badge--align-${align}`,
    transparent && 'dss-badge--transparent',
    outline && 'dss-badge--outline',
    rounded && 'dss-badge--rounded',
    multiLine && 'dss-badge--multi-line',
    isEmpty && 'dss-badge--empty',
    className
  ].filter(Boolean).join(' ');

  return (
    <span
      className={classes}
      aria-label={ariaLabel}
      {...props}
    >
      {children || label}
    </span>
  );
}

// packages/core/components/base/DssBadge/1-structure/DssBadge.vue
<template>
  <div
    :class="badgeClasses"
    :style="badgeStyle"
  >
    <!-- Conteúdo do badge -->
    <slot>{{ label }}</slot>
  </div>
</template>

<script>
export default {
  name: 'DssBadge',

  props: {
    // Conteúdo
    label: {
      type: [Number, String],
      default: ''
    },

    // Cores (compatível com Quasar)
    color: {
      type: String,
      default: 'primary',
      validator: (value) => ['primary', 'secondary', 'tertiary', 'accent', 'positive', 'negative', 'warning', 'info'].includes(value)
    },
    textColor: {
      type: String,
      default: null
    },

    // Posicionamento (compatível com Quasar)
    floating: {
      type: Boolean,
      default: false
    },
    align: {
      type: String,
      default: null,
      validator: (value) => !value || ['top', 'middle', 'bottom'].includes(value)
    },

    // Aparência (compatível com Quasar)
    transparent: {
      type: Boolean,
      default: false
    },
    multiLine: {
      type: Boolean,
      default: false
    },
    outline: {
      type: Boolean,
      default: false
    },
    rounded: {
      type: Boolean,
      default: false
    }
  },

  computed: {
    badgeClasses() {
      // Determina cores seguindo padrão Quasar (QBadge)
      // outline/transparent: usa text-{color}
      // normal: usa bg-{color}
      const text = this.outline === true || this.transparent === true
        ? this.color
        : this.textColor;

      let colorClasses = '';
      if (this.outline === true || this.transparent === true) {
        // outline/transparent: apenas cor de texto
        colorClasses = `text-${this.color}`;
      } else {
        // normal: background + texto branco
        colorClasses = `bg-${this.color} text-white`;
      }

      // Override de text color se especificado
      if (this.textColor) {
        colorClasses += ` text-${this.textColor}`;
      }

      return [
        'dss-badge',
        colorClasses, // Classes utilitárias (.bg-primary, .text-primary)
        {
          'dss-badge--floating': this.floating,
          'dss-badge--transparent': this.transparent,
          'dss-badge--multi-line': this.multiLine,
          'dss-badge--outline': this.outline,
          'dss-badge--rounded': this.rounded
        }
      ];
    },

    badgeStyle() {
      const style = {};

      // Vertical align (compatível com Quasar)
      if (this.align) {
        style.verticalAlign = this.align;
      }

      return style;
    }
  }
}
</script>

<!-- Estilos carregados globalmente via dss-full.css -->
